### ISSUE TITLE
The cache dosent save included associations

### ISSUE THREAD

**Issue by pabloascarza** [idangozlan/sequelize-redis#1]
Hi im using this whit
`` 		const [user, cacheHit] = await this.User.findByIdCached('1_p', 1, {
			include: ['role']
		});``
and when is not cached it return the included role, but when the data cames from the cache it dosent. Any suggestion how to proceed? Or its simply not supported.

**Comment by idangozlan** [comment]
Hi, 
Can you please provide an reproducable code?

**Comment by pabloascarza** [comment]
Sure, sry about that whit a litle config of bd this code has to work

``import Sequelize from 'sequelize';
import SequelizeRedis from 'sequelize-redis';
import * as redis from 'redis';
import { promisifyAll } from 'bluebird';

const sequelize = new Sequelize(database, pername, password, {
	host: host,
	dialect: dialect,
	storage: storage
});

sequelize.define('permission', {});
sequelize.define('role', {
	name: {
		type: Sequelize.STRING,
	},
	code: {
		type: Sequelize.STRING,
		unique: true
	},
});

let PermissionModel = sequelize.model('permission');
let RoleModel = sequelize.model('role');

PermissionModel.belongsTo(RoleModel, {as: 'role'});

promisifyAll(redis.RedisClient.prototype);
promisifyAll(redis.Multi.prototype);
const redisClient = redis.createClient({host: 'redis', password: 'redis'});
const sequelizeRedis = new SequelizeRedis(redisClient);

PermissionModel = sequelizeRedis.getModel(PermissionModel, { ttl: 60 * 60 * 24 });

let role = await RoleModel.create({name: 'admin', code: 'admin});
let permission = await RoleModel.create({roleId: role.id});

// first time from db.. it returns the code
const [per, cacheHit] = await PermissionModel.findByIdCached('1_p', 1, {
    include: ['role']
});

console.log('per', per.toJSON(), 'cacheHit', cacheHit, 'per.role.code', per.role ? per.role.code : "not included");

// second time from cache.. it returns code = "not included"
const [per, cacheHit] = await PermissionModel.findByIdCached('1_p', 1, {
    include: ['role']
});

console.log('per', per.toJSON(), 'cacheHit', cacheHit, 'per.role.code', per.role ? per.role.code : "not included");``

**Comment by pabloascarza** [comment]
``

**Comment by ricardomoura** [comment]
did a PR for this issue guys

**Comment by idangozlan** [comment]
v1.0.8 is now available. enjoy and thanks to @ricardomoura .
